### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Wyrmwood** [RPTools/maptool#3310]
### Describe the Bug

java.lang.NullPointerException: Cannot invoke "net.rptools.maptool.model.InitiativeList$TokenInitiative.isHolding()" because "oldti" is null
	at net.rptools.maptool.model.Zone.<init>(Zone.java:546)
	at net.rptools.maptool.model.Campaign.<init>(Campaign.java:172)
	at net.rptools.maptool.client.AutoSaveManager.executeAndContinue(AutoSaveManager.java:102)
	at net.rptools.maptool.client.AutoSaveManager.execute(AutoSaveManager.java:63)
	at net.rptools.maptool.client.AutoSaveManager.lambda$start$0(AutoSaveManager.java:49)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at net.rptools.maptool.client.swing.MapToolEventQueue.dispatchEvent(MapToolEventQueue.java:54)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### To Reproduce

I have seen this several times, but I am not entirely clear as to what leads up to it. Every time it has happened, I have reopened a campaign file that was saved with the initiative window open and populated, and with an onInitiativeChange macro. I have not been using initiative hold. I tried reproducing in an empty campaign file, with two tokens added to initiative, but was unable to.

My suspicion is whatever oldti represents is not being serialized during save, so on load, the information is unavailable. 

### Expected Behaviour

All initiative data from the previous campaign file should be available on load.

### MapTool Info

MapTool Version: 1.11.4

### Desktop

Windows 10, Microsoft Windows [Version 10.0.19044.1415] 21H2

### Additional Context

==== MapTool Information ====
MapTool Version: 1.11.4
MapTool Home...: C:\Users\wyrmwood\.maptool-rptools
MapTool Install: C:\Users\wyrmwood\AppData\Local\MapTool\app
Max mem avail..: 3 GB
Max mem used...: 948 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\wyrmwood\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\wyrmwood\AppData\Local\MapTool\runtime
Java Vendor....: Eclipse Foundation
Java Version...: 16.0.2
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\wyrmwood\AppData\Local\MapTool\MapTool.exe

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
PATH...........: C:\Users\wyrmwood\AppData\Local\MapTool;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Gow\bin;C:\Program Files (x86)\Brewtarget-2.3.0\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Python\Python37-32\Scripts\;C:\Python\Python37-32\;C:\Users\wyrmwood\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\wyrmwood\AppData\Local\Programs\Python\Python37-32\;C:\Users\wyrmwood\AppData\Local\Microsoft\WindowsApps;C:\Users\wyrmwood\Dropbox\sql\sqlite-tools-win32-x86-3260000;C:\Program Files\Sublime Text 3;C:\Program Files\Oracle\VirtualBox;C:\Users\wyrmwood\VcXsrv;C:\Users\wyrmwood\scripts;C:\Users\wyrmwood\MapTool;C:\Program Files\GIMP 2.10\bin;C:\Program Files\GIMP 2.8\bin;C:\Users\wyrmwood\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files (x86)\pypy3.7-v7.3.2-win32;E:\src\dnd5e.mt;C:\Program Files\PuTTY;C:\Users\wyrmwood\AppData\Local\MapTool\;C:\Program Files (x86)\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2021.1.1\bin;;C:\Users\wyrmwood\platform-tools_r31.0.2-windows\platform-tools;;.
Number of Procs: 16

==== User Information ====
User Name: wyrmwood
User Home: C:\Users\wyrmwood
User Dir.: C:\Users\wyrmwood\AppData\Local\MapTool

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: VirtualBox Host-Only Ethernet Adapter
Interface Name: eth4
Address...: 192.168.56.1
Address...: fe80:0:0:0:a950:3a70:6edb:ee86%eth4

Display Name..: Realtek PCIe GBE Family Controller
Interface Name: eth10
Address...: 192.168.0.207
Address...: fe80:0:0:0:6864:7a9e:efdc:f9fd%eth10

Display Name..: Hyper-V Virtual Ethernet Adapter
Interface Name: eth21
Address...: 172.20.208.1
Address...: fe80:0:0:0:58a4:9bcc:9901:2f11%eth21

Display Name..: Hyper-V Virtual Ethernet Adapter #2
Interface Name: eth38
Address...: 172.20.176.1
Address...: fe80:0:0:0:808f:4f61:2859:1e6%eth38

Host Address...: 192.168.56.1
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 3840x2160(32)
Display 2: 3840x2160(32)

==== Internet Gateway Devices ====
Device Name.: Archer AX1800
Model Name..: Archer AX1800
Manufacturer: TP-Link
Model Number: 1.20
Model Desc..: Archer AX1800
Firmware....: TP-LINK/TP-LINK UPnP/1.1 MiniUPnPd/1.8
External IP.: 73.203.62.112

**Comment by adyoungblood** [comment]
Would you mind sending the campaign file in which you are encountering this issue? Being able to reproduce the bug would make the process of fixing it a whole lot easier.

**Comment by Wyrmwood** [comment]
km.tgz
<https://drive.google.com/file/d/137uI_VU6F58yzIcYvBIh-txdGYFg4xRi/view?usp=drive_web>

Regards,
John Felps

וצריך ביאור
*One way is to make it so simple that there are obviously no deficiencies,
and the other way is to make it so complicated that there are no obvious
deficiencies. - Tony Hoare*

**Comment by adyoungblood** [comment]
Alright, I'm investigating the issue now.

**Comment by Phergus** [comment]
@adyoungblood did you figure anything out on this?

**Comment by Phergus** [comment]
Unable to reproduce this.  Moving to backlog.

**Comment by cwisniew** [comment]
I have tried several times to reproduce this with no luck. So I have added error logging to where I think the error is occurring to provide further information.

**Comment by kwvanderlinde** [comment]
I have encountered something similar once a few weeks ago (I _think_ it was exactly this error) when running a game. I had a server running, plus 6 more clients connected. In the mayhem of everyone adding themselves to initiative, plus me trying to correct mistakes server side, the initiative list between the server and clients became desynchronized and (as I recall) everyone was shown an error dialog. After dismissing those, anytime we tried to use initiative list functionality on the server and error would been shown like the one mentioned by OP. I fixed it by manually working the server initiative list to agree with one of the client (apparently all the clients agreed actually).

Unfortunately I haven't seen that again so haven't been able to debug it at all. I also never saved the campaign in that state, so can't just reload it and test. But maybe that gives an avenue to explore for why this could happen. Or this could just be another way to see the same symptom.

**Comment by emmebi** [comment]
I can confirm that this is still happening with MapTool 1.12, and I have seen it multiple times with previous versions.

I don't have the logs for the last occurrence (had to clean up the cache for a different problem), but I will post logs as soon as I have them.

**Comment by emmebi** [comment]
I think this is a duplicate: https://github.com/RPTools/maptool/issues/2776

**Comment by thelsing** [comment]
Maybe it's related to connecting before campaign was set after server start.
